### ISSUE TITLE
Allow select typed ?

### ISSUE THREAD

**Issue by abalad** [amcdnl/ngxs#40] opened 2018-03-05 21:13 UTC
Is there a way to pass the state type to Select? 

 // Also accepts a function like our select method
`  @Select(state => state.animals) animals$: Observable<string[]>;`
as 
`  @Select(state<StateType> => state.animals) animals$: Observable<string[]>;`

**Comment by deebloo** [comment] 2018-03-05 21:27
@abalad adding better type safety is something I am working on. Not sure how we will handle it for the select decorator but we shall see

**Comment by amcdnl** [comment] 2018-03-06 01:34
Dupe of #25

**Closed by amcdnl** 2018-03-06 01:34 UTC
